#Importing necessary libraries


In [87]:
import numpy as np
import pandas as pd
import sklearn


# Loading Iris flower dataset


In [88]:
from sklearn.datasets import load_iris
data = load_iris()
print("Feature names = " ,data.feature_names)
print("Target names = " ,data.target_names)


Feature names =  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names =  ['setosa' 'versicolor' 'virginica']


In [89]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

#Convert the data to a pandas DataFrame


In [90]:
iris_df = pd.DataFrame(data.data, columns=data.feature_names)
iris_df['target'] = data.target
iris_df



sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

# Data Insights

In [91]:
iris_df.describe()


sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

# Separate features and target

In [92]:
data=iris_df.values
X=data[:,0:4]
Y=data[:,4]
print("X" , X)
print("Y" , Y)



X [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 

# Splitting training and test data

In [93]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,Y, test_size=0.2)

In [94]:
print(X_train.shape)
print(X_train)

print(y_train.shape)
print(y_train)

print(y_test.shape)
print(y_test)

print(X_test.shape)
print(X_test)




(120, 4)
[[6.2 3.4 5.4 2.3]
 [7.7 2.6 6.9 2.3]
 [5.7 2.8 4.5 1.3]
 [4.4 3.  1.3 0.2]
 [5.4 3.7 1.5 0.2]
 [6.3 2.7 4.9 1.8]
 [5.6 2.8 4.9 2. ]
 [4.9 2.4 3.3 1. ]
 [4.3 3.  1.1 0.1]
 [6.4 2.8 5.6 2.2]
 [5.1 3.5 1.4 0.3]
 [5.  2.3 3.3 1. ]
 [6.4 3.2 5.3 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.  5.5 2.1]
 [7.3 2.9 6.3 1.8]
 [5.2 3.5 1.5 0.2]
 [4.8 3.4 1.9 0.2]
 [5.2 4.1 1.5 0.1]
 [6.4 3.1 5.5 1.8]
 [7.4 2.8 6.1 1.9]
 [5.7 2.5 5.  2. ]
 [5.7 4.4 1.5 0.4]
 [6.5 3.  5.5 1.8]
 [5.1 3.3 1.7 0.5]
 [5.7 2.6 3.5 1. ]
 [5.2 3.4 1.4 0.2]
 [6.4 2.9 4.3 1.3]
 [6.9 3.1 5.1 2.3]
 [6.3 3.3 6.  2.5]
 [7.7 2.8 6.7 2. ]
 [6.1 2.9 4.7 1.4]
 [5.8 4.  1.2 0.2]
 [5.6 2.5 3.9 1.1]
 [6.1 2.8 4.7 1.2]
 [5.  3.5 1.6 0.6]
 [4.6 3.2 1.4 0.2]
 [5.1 3.5 1.4 0.2]
 [6.3 2.8 5.1 1.5]
 [6.7 3.1 4.7 1.5]
 [5.6 3.  4.5 1.5]
 [6.2 2.9 4.3 1.3]
 [5.8 2.7 5.1 1.9]
 [6.2 2.2 4.5 1.5]
 [5.4 3.9 1.3 0.4]
 [5.  3.6 1.4 0.2]
 [5.1 3.4 1.5 0.2]
 [6.7 3.  5.  1.7]
 [5.  2.  3.5 1. ]
 [5.3 3.7 1.5 0.2]
 [6.9 3.1 4.9 1.5]
 [6.3 2.5 4.9 1.5]
 [6

# Model 1: Support Vector Machine Algorithm

In [95]:
from sklearn.svm import SVC

model_svc=SVC()
model_svc.fit(X_train,y_train)

SVC()

In [96]:
prediction1 = model_svc.predict(X_test)

#calculate the accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, prediction1))

0.9333333333333333


# Model 2: Logistic Regression

In [98]:
from sklearn.linear_model import LogisticRegression
model= LogisticRegression()
model.fit(X,Y)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [99]:
model.score(X,Y)

0.9733333333333334

# Check Prediction

In [104]:
expected = Y
predicted = model.predict(X)
# predicted
expected == predicted

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

# Model 3: Decision Tree Classifier

In [105]:
from sklearn.tree import DecisionTreeClassifier
model_DTC = DecisionTreeClassifier()
model_DTC.fit(X_train, y_train)


prediction3= model_svc.predict(X_test)

#calculate the accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, prediction3))

0.9333333333333333
